import { Inter,Montserrat } from 'next/font/google'
import  './globals.css'
import Nav from './componant/nav/Nav'
import Footer from './componant/footer/Footer'
import ThemeProvider from '@/context/ThemeContext'


const inter = Inter({ subsets: ['latin']})
const logo =   Montserrat({ subsets: ['latin'] ,
weight:['100','300','400','900']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={logo.className}>
  <ThemeProvider>

  <div className='container'>
          <Nav/>
         {children}
         <Footer/>
     </ div>
   
  </ThemeProvider>
     
   
        </body>
    </html>
  )   
}
